### ISSUE TITLE
Complete RtXmlRpcReference

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyroscope/pyroscope#43]
```
This page is really useful:

https://code.google.com/p/pyroscope/wiki/RtXmlRpcReference

It's more complete than the original docs @ rTorrent, I wish you guys find the 
time to complete it.
```

Original issue reported on code.google.com by `apatheti...@gmail.com` on 28 Jul 2013 at 11:17

**Comment by pyroscope** [comment]
I wish **you** guys would be a community that supported such efforts by text contributions. :smirk:

"Won't fix" as long as I'm alone in the effort.
