### ISSUE TITLE
~/lib/pyroscope/update-to-head.sh error

### ISSUE THREAD

**Issue by exexex** [pyroscope/pyroscope#50]
Using Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2]
Updating your installation...
Already up-to-date.
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already up-to-date: setuptools>=0.6c11 in ./lib/python2.7/site-packages
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already up-to-date: paver>=1.0.5 in ./lib/python2.7/site-packages
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already up-to-date: yolk3k in ./lib/python2.7/site-packages
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already up-to-date: Tempita>=0.5.1 in ./lib/python2.7/site-packages
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already up-to-date: APScheduler>=2.0.2 in ./lib/python2.7/site-packages
Requirement already up-to-date: six in ./lib/python2.7/site-packages (from APScheduler>=2.0.2)
Requirement already up-to-date: futures in ./lib/python2.7/site-packages (from APScheduler>=2.0.2)
Requirement already up-to-date: pytz in ./lib/python2.7/site-packages (from APScheduler>=2.0.2)
Requirement already up-to-date: tzlocal in ./lib/python2.7/site-packages (from APScheduler>=2.0.2)
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already up-to-date: waitress>=0.8.2 in ./lib/python2.7/site-packages
Requirement already up-to-date: setuptools in ./lib/python2.7/site-packages (from waitress>=0.8.2)
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already up-to-date: WebOb>=1.2.3 in ./lib/python2.7/site-packages
warning: no files found matching 'setup.py'
warning: no files found matching 'paver-minilib.zip'
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): Tempita>=0.5.1 in ./lib/python2.7/site-packages
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): APScheduler>=2.0.2 in ./lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): six in ./lib/python2.7/site-packages (from APScheduler>=2.0.2)
Requirement already satisfied (use --upgrade to upgrade): futures in ./lib/python2.7/site-packages (from APScheduler>=2.0.2)
Requirement already satisfied (use --upgrade to upgrade): pytz in ./lib/python2.7/site-packages (from APScheduler>=2.0.2)
Requirement already satisfied (use --upgrade to upgrade): tzlocal in ./lib/python2.7/site-packages (from APScheduler>=2.0.2)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: Project 'pyrobase' is not initialized!
warning: no files found matching 'setup.py'
warning: no files found matching 'paver-minilib.zip'
warning: no files found matching 'setup.py'
warning: no files found matching 'paver-minilib.zip'
ln: ‘./bin’: cannot overwrite directory
/home/vigour/lib/pyroscope/update-to-head.sh: line 66: ./bin/pyroadmin: No such file or directory

Ubuntu 15.04

**Comment by pyroscope** [comment]
"Open new issues in the tracker of the respective new project; new issues opened here will be instantly closed." (see readme)

I guess this is a dupe anyway.
