### ISSUE TITLE
rtcontrol using old command "d.set_custom"

### ISSUE THREAD

**Issue by TwoLeaves** [pyroscope/pyroscope#51]
I'm getting a mismatch in the commands used in rtorrent and pyroscope. Specifically when running rtcontrol using this command (as per the [ArchLinux wiki instructions on Pyroscope](https://wiki.archlinux.org/index.php/RTorrent#PyroScope)):
```
rtcontrol '!*"*' loaded=0 -q -sname -o 'echo "$(name)s"\ntest -f "$(metafile)s" && rtxmlrpc -q d.set_custom $(hash)s tm_loaded \$(\
    ls -l --time-style "+%%s" "$(metafile)s" \
    | cut -f6 -d" ")\nrtxmlrpc -q d.save_session $(hash)s' | bash
```
I'm getting this error:
```
(2004) Arular
INFO: Bad data packets written to '/tmp/xmlrpc2scgi-0.xml'
ERROR    While calling d.set_custom('16BF8C8483286146BB9888E7DF52594307F8BCFF', 'tm_loaded', '1444207375'): <Fault -506: "Method 'd.set_custom' not defined">
```

I'm the latest HEAD of both rtorrent-ps and the pyroscrope tools on ArchLinux

Where is the call to d.set_custom coming from? The Pyroscope code? My rtorrent config? A field recorded per torrent by rtorrent in its session data? All my torrent files were added to a fresh rtorrent installation with the new command style so the latter doesn't make sense. I also tried replacing the old-style call with the new-style call in the pyroscope code but to no avail. My full config is here: (http://sprunge.us/KacS). Thank you.

**Comment by TwoLeaves** [comment]
Similarly I am getting ```Scheduled command failed: update_last_active: Command "d.multicall" does not exist.``` in the rtorrent log.

**Comment by pyroscope** [comment]
Open new issues in the tracker of the respective new project; new issues opened here will be instantly closed. (read the readme) fixed anyway.
